import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from '@/components/Weather'
import Loading from '@/components/Loading'


export default function Home() {

  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({})
  const [loading, setLoading] = useState(false)
  const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
  axios.get(url).then((response) => {
    setWeather(response.data)
  })
  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
    })
    setLoading(false)
  }
  return (
    <>
      <Head>
        <title>Nextjs Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className='absolute top-0 left-0 right-0 bottom-0 z-[1] bg-black/60'></div>
        <Image 
          src='https://images.unsplash.com/photo-1561484930-998b6a7b22e8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8'
          fill='true'
          alt='background'
          className='object-cover'>

        </Image>
        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
          <form onSubmit={fetchWeather} className='relative flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-xl'>
            <div>
              <input onChange={(e)=>setCity(e.target.value)} className='border-none bg-transparent text-white focus:outline-none w-full text-xl' type='text' placeholder='Search city'/>
            </div>
            <button className='text-neutral-100' onClick={fetchWeather}><BsSearch className='font-semibold' size={20}></BsSearch></button>
          </form>
        </div>
        { loading && <Loading /> }
        { weather.main && <Weather data={weather}/>}
        
      
    </>
  )
}
